[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pytest-example"
version = "0.1.0"
dependencies = []
requires-python = ">=3.11"

[project.optional-dependencies]
dev = ["pytest", "pytest-opentelemetry"]
